/* Generated by automated build script */
#define PRERELEASE 0.79
#define TEXTVER "Pre-release 0.79:2023-08-24.27f0140"
#define SSHVER "-Prerelease-0.79:20230824.27f0140"
#define BINARY_VERSION 0,78,34068,0
