/* Generated by automated build script */
#define SNAPSHOT
#define TEXTVER "Development snapshot 2016-04-17.b22c0b6"
#define SSHVER "PuTTY-Snapshot-2016-04-17.b22c0b6"
#define BINARY_VERSION 0,67,1048,0
