/* Generated by automated build script */
#define PRERELEASE 0.79
#define TEXTVER "Pre-release 0.79:2023-05-22.56b16bd"
#define SSHVER "-Prerelease-0.79:20230522.56b16bd"
#define BINARY_VERSION 0,78,33974,0
