'\" t
.\"     Title: ne_ssl_set_protovers
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 15 April 2025
.\"    Manual: neon API reference
.\"    Source: neon 0.34.2
.\"  Language: English
.\"
.TH "NE_SSL_SET_PROTOVERS" "3" "15 April 2025" "neon 0.34.2" "neon API reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ne_ssl_set_protovers \- set session SSL/TLS minimum or maximum protocol version
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <ne_session\&.h>
.fi
.ft
.HP \w'int\ ne_ssl_set_protovers('u
.BI "int ne_ssl_set_protovers(ne_session\ *" "sess" ", enum\ ne_ssl_protocol\ " "min" ", enum\ ne_ssl_protocol\ " "max" ");"
.SH "DESCRIPTION"
.PP
The
\fBne_ssl_set_protovers\fR
function sets the minimum and/or maximum SSL/TLS version\&. Either minimum and/or maximum may be specified as
\fBNE_SSL_PROTO_UNSPEC\fR, in which case no limit is imposed\&.
.SH "RETURN VALUE"
.PP
The
\fBne_ssl_set_protovers\fR
function returns zero on success or non\-zero on error\&. Errors include an invalid range (minimum above maximum), or if the protocol version is not supported by the SSL/TLS toolkit in use, or if SSL/TLS is not in use for the session\&.
.SH "HISTORY"
.PP
\fBne_ssl_set_protovers\fR
is available in neon 0\&.34\&.0 and later\&.
.SH "SEE ALSO"
.PP
ne_ssl_proto_name,
ne_session_create\&.
.SH "COPYRIGHT"
.br
Copyright \(co 2001-2024 Joe Orton
.br
