#ifndef HelpCoreH
#define HelpCoreH

#define HELP_UNKNOWN_KEY                       "message_host_key"
#define HELP_DIFFERENT_KEY                     "message_security_breach"
#define HELP_RESUME_TRANSFER                   "resume"
#define HELP_APPEND_OR_RESUME                  "resume#manual"
#define HELP_PARTIAL_BIGGER_THAN_SOURCE        HELP_RESUME_TRANSFER
#define HELP_SYNCHRONIZE                       "task_synchronize_full"
#define HELP_VERIFY_CERTIFICATE                "ftps"
#define HELP_FTP_CANNOT_OPEN_ACTIVE_CONNECTION "message_cannot_open_active_connection"
#define HELP_MESSAGE_HOST_IS_NOT_COMMUNICATING "message_host_is_not_communicating"
#define HELP_ERRORMSG_TIMEOUT                  "message_timeout_detected"
#define HELP_OVERWRITE                         "ui_overwrite"
#define HELP_NET_TRANSL_REFUSED                "message_connection_refused"
#define HELP_NET_TRANSL_TIMEOUT                "message_connection_timed_out"
#define HELP_NET_TRANSL_NO_ROUTE               "message_no_route_to_host"
#define HELP_NET_TRANSL_CONN_ABORTED           "message_software_caused_connection_abort"
#define HELP_NET_TRANSL_HOST_NOT_EXIST         "message_host_does_not_exist"
#define HELP_SFTP_STATUS_FAILURE               "sftp_codes#code_4"
#define HELP_UNEXPECTED_CLOSE_ERROR            "message_unexpected_close"
#define HELP_NET_TRANSL_PACKET_GARBLED         "message_incoming_packet_was_garbled_on_decryption"
#define HELP_NOT_CONNECTED                     "message_exit_status_1"
#define HELP_SFTP_STATUS_PERMISSION_DENIED     "message_permission_denied"
#define HELP_NET_TRANSL_RESET                  "message_reset_by_peer"
#define HELP_LIST_LINE_ERROR                   "message_unexpected_directory_listing"
#define HELP_SFTP_PACKET_TOO_BIG               "message_large_packet"
#define HELP_SKIP_STARTUP_MESSAGE_ERROR        "message_startup_message"
#define HELP_EMPTY_DIRECTORY                   "message_empty_listing_for_directory"
#define HELP_RENAME_AFTER_RESUME_ERROR         "message_transfer_finished_could_not_rename"
#define HELP_INTERNAL_ERROR                    "internal_error"
#define HELP_PRESERVE_TIME_PERM_ERROR          "message_preserve_time_perm"
#define HELP_FTP_SUGGESTION                    "message_server_rejected_sftp_listens_for_ftp"
#define HELP_STATUSMSG_DISCONNECTED            "message_disconnected"
#define HELP_SFTP_INITIALIZE_ERROR             "message_cannot_initialize_sftp_protocol"
#define HELP_AUTH_TRANSL_KEY_REFUSED           "message_key_refused"
#define HELP_FILE_ENCRYPTION                   "file_encryption"

#endif // HelpCoreH
