#ifndef HelpWinH
#define HelpWinH

#define HELP_ERROR                   "messages"
#define HELP_SESSION_SAVE            "ui_login_save"
#define HELP_SESSION_SAVE_OVERWRITE  HELP_SESSION_SAVE
#define HELP_SESSION_SAVE_DEFAULT    "ui_login#management"
#define HELP_CREATE_SHORTCUT         "integration"
#define HELP_CREATE_SENDTO           HELP_CREATE_SHORTCUT
#define HELP_CREATE_ICON             HELP_CREATE_SHORTCUT
#define HELP_REGISTER_URL            HELP_CREATE_SHORTCUT
#define HELP_ADD_SEARCH_PATH         HELP_CREATE_SHORTCUT
#define HELP_EDIT_NEW                "task_edit"
#define HELP_LOCATION_PROFILE_ADD    "ui_locationprofile"
#define HELP_LOCATION_PROFILE_MOVE   HELP_LOCATION_PROFILE_ADD
#define HELP_LOCATION_PROFILE_DELETE HELP_LOCATION_PROFILE_ADD
#define HELP_REMOTE_MOVE             "task_move_duplicate"
#define HELP_CUSTOM_COMMAND_PARAM    "custom_command"
#define HELP_SYNCHRONIZE_SAVE_MODE   "ui_synchronize"
#define HELP_PROGRESS_CANCEL         "ui_progress#controlling"
#define HELP_KEEPUPTODATE_SYNCHRONIZE "task_keep_up_to_date"
#define HELP_DD_WARN_LACK_OF_TEMP_SPACE "ui_pref_dragdrop#temporary"
#define HELP_EDITOR_EARLY_CLOSED     "task_edit#mdi"
#define HELP_APP_EARLY_CLOSED        HELP_EDITOR_EARLY_CLOSED
#define HELP_OPEN_FILE_NO_PROCESS    HELP_EDITOR_EARLY_CLOSED
#define HELP_ADD_BOOKMARK_CONFIRM    "task_navigate#bookmarks"
#define HELP_PERFORM_ON_COMMAND_SESSION "shell_session"
#define HELP_COPY_PARAM_AUTOSELECTED "transfer_settings#presets"
#define HELP_CLEAN_TEMP_CONFIRM      "temp_folders"
#define HELP_UPDATES                 "updates"
#define HELP_COMPARE_NO_DIFFERENCES  "task_compare_directories"
#define HELP_SYNC_DIR_BROWSE_ERROR   "task_navigate#synchronize_browsing"
#define HELP_UNINSTALL_CLEANUP       "ui_cleanup"
#define HELP_EDITOR_FIND             "ui_editor_find"
#define HELP_EDITOR_REPLACE          "ui_editor_replace"
#define HELP_DELETE_SESSION          "ui_login#management"
#define HELP_DELETE_SESSION_FOLDER   HELP_DELETE_SESSION
#define HELP_DELETE_WORKSPACE        HELP_DELETE_SESSION
#define HELP_NEW_SESSION_FOLDER      HELP_DELETE_SESSION
#define HELP_TOO_MANY_WATCH_DIRECTORIES "ui_keepuptodate"
#define HELP_LOGIN_KEY_TYPE          "public_key#private"
#define HELP_SYNCHRONIZE_NO_DIFFERENCES "task_synchronize_full"
#define HELP_MASTER_PASSWORD_CURRENT "ui_master_password"
#define HELP_MASTER_PASSWORD_CHANGE  "ui_master_password_change"
#define HELP_MASTER_PASSWORD         "master_password"
#define HELP_MASTER_PASSWORD_SIMPLE  HELP_MASTER_PASSWORD
#define HELP_USAGE                   "usagestatistics"
#define HELP_WORKSPACE_SAVE          "ui_save_workspace"
#define HELP_EDITOR_AUTO_CONFIG      "ui_pref_editor#auto"
#define HELP_IMPORT_SESSIONS         "ui_import"
#define HELP_IMPORT_CONFIGURATION    "config"
#define HELP_MOVE_CONFIGURATION      HELP_IMPORT_CONFIGURATION
#define HELP_DELETE_FILE             "task_delete"
#define HELP_COLOR                   "task_connections#session_color"
#define HELP_DRAGEXT_TARGET_UNKNOWN  "dragext"
#define HELP_KEY_TYPE_UNSUPPORTED    "ui_puttygen#other_formats"
#define HELP_TIPS                    "ui_tips"
#define HELP_DEBUGGING               "debugging"
#define HELP_EXTENSION_OPTIONS       "ui_pref_commands"
#define HELP_CHANGE_PASSWORD         "task_change_password"
#define HELP_FILTER                  "ui_filter"
#define HELP_LOGIN_AUTHORIZED_KEYS   "guide_public_key"
#define HELP_READONLY_INI_FILE       "config#ini_readonly"
#define HELP_TAB_RENAME              "ui_tabs#renaming"
#define HELP_DD_TARGET_UNKNOWN       "ui_pref_dragdrop#fake_file"
#define HELP_FILE_COLORS             "ui_file_color"
#define HELP_AUTOMATIC_UPDATE        "updates#automatic_upgrade"
#define HELP_SITE_RAW                "ui_login_raw"
#define HELP_PUTTY_SETTINGS          "ui_login_environment#putty"
#define HELP_CLOSE_SESSION_WORKSPACE "workspace"
#define HELP_ADD_EXTENSION           "ui_pref_commands#extensions"
#define HELP_TOO_MANY_SESSIONS       "ui_tabs"
#define HELP_STORE_TRANSITION        "microsoft_store#transitioning"
#define HELP_SSH_HOST_CA             "ui_ssh_host_ca"
#define HELP_SHOW_LOGIN              "ui_pref_window#show_login"
#define HELP_TAG                     "ui_properties#tags"

#endif // TextsWin
